name = "A Block and a Hard Place"
author = "GrandmaPork"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bca18c6909f3dc036b8f86bea40488c063e855ffbdae81553b8d230efe8da7cf"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
