name = "A Block and a Hard Place"
author = "GrandmaPork"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a578adab87d148a5cd17b1661764b0da5d1ac3a22df7d68c73e17fcc555f2d0c"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
