name = "A Block and a Hard Place"
author = "GrandmaPork"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2754448a3068c3364049fe8543d2183162a854bd6c86ae4eaf4697a15a4c6371"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
